[build]
  publish = "build/web"
  command = """
  git clone https://github.com/flutter/flutter.git --depth 1 -b stable
  export PATH="$PATH:$PWD/flutter/bin"
  flutter config --enable-web
  flutter build web --release
  """
